Advanced Programming : TLS handshake: include/HandshakeMessages/Certificate.h File Reference
Certificate.h File Reference
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <openssl/x509.h>
#include <openssl/pem.h>
#include "TLSConstants.h"
Data Structures
struct certificate_message_t
Functions
certificate_message_t * make_certificate_message (char *cert_file_name)
void serialize_certificate_message (certificate_message_t *cert, unsigned char **stream, uint32_t *len)
certificate_message_t * deserialize_certificate_message (unsigned char *stream, uint32_t len)
void free_certificate_message (certificate_message_t *cert)
Detailed Description
SSL/TLS Project
This file contains functions to manage the certificate message.
Date
Created on 28/12/15.
Copyright
Copyright © 2015 Alessandro Melloni, Andrea Francesco Vinci. All rights reserved.
Function Documentation
certificate_message_t* deserialize_certificate_message (unsigned char * stream, uint32_t len)
De-serialize a byte stream into a certificate_message.
Parameters
stream the byte stream to de-serialize
len the byte stream length
Returns
the certificate_message
Referenced by onPacketReceive(), and print_handshake().
void free_certificate_message (certificate_message_t * cert)
Dealloc memory of certificate_message
Parameters
cert the certificate message to deallocate
Referenced by make_certificate(), onPacketReceive(), and print_handshake().
certificate_message_t* make_certificate_message (char * cert_file_name)
Given the certificate file name create a certificate message struct that encapsulate it.
Parameters
cert_file_name certificate file name including path
Returns
the certificate message struct
Referenced by make_certificate().
void serialize_certificate_message (certificate_message_t * cert, unsigned char ** stream, uint32_t * len)
Serialize the certificate message into a byte stream
Parameters
cert the message to serialize
stream the return stream. Must point to NULL.
len the stream length
Serialize the certificate message into a byte stream
Parameters
cert the message to serialize
stream the return stream. Must point to NULL
len the stream length
Referenced by make_certificate().