Advanced Programming : TLS handshake: include/Crypto.h File Reference
Crypto.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <openssl/rand.h>
#include <openssl/pem.h>
#include <openssl/rsa.h>
#include "TLSConstants.h"
#include "ServerClientKeyExchange.h"
Functions
void PRF (const EVP_MD *hash, unsigned char *secret, int secret_len, char *label, unsigned char *seed, int seed_len, int result_len, unsigned char **result)
int sign_DHE_server_key_ex (unsigned char *client_random, unsigned char *server_random, dhe_server_key_exchange_t *server_key_ex, authentication_algorithm au)
int verify_DHE_server_key_ex_sign (X509 *certificate, unsigned char *client_random, unsigned char *server_random, dhe_server_key_exchange_t *server_key_ex, authentication_algorithm au)
int sign_ECDHE_server_key_ex (unsigned char *client_random, unsigned char *server_random, ecdhe_server_key_exchange_t *server_key_ex, authentication_algorithm au)
int verify_ECDHE_server_key_ex_sign (X509 *certificate, unsigned char *client_random, unsigned char *server_random, ecdhe_server_key_exchange_t *server_key_ex, authentication_algorithm au)
Detailed Description
SSL/TLS Project
PRF function and sign/verify function. The follow functions wrap openssl library for sign, verify.
Date
Created on 27/12/15.
Copyright
Copyright © 2015 Alessandro Melloni, Andrea Francesco Vinci. All rights reserved.
Function Documentation
void PRF (const EVP_MD * hash, unsigned char * secret, int secret_len, char * label, unsigned char * seed, int seed_len, int result_len, unsigned char ** result)
Apply the PRF to a secret.
Parameters
hash : the hash to use in the hmac
secret : the secret to process
secret_len : secrete length
label : the label of the PRF computation
seed : the seed for the computation
seed_len : seed length
result : a pointer to char, will contain the result after computation. Must point to NULL
result_len : the desired length of pseudo random stream.
Referenced by compute_set_master_key_DHE(), compute_set_master_key_ECDHE(), compute_set_master_key_RSA(), make_DHE_client_key_exchange(), make_ECDHE_client_key_exchange(), make_finished_message(), and make_RSA_client_key_exchange().
int sign_DHE_server_key_ex (unsigned char * client_random, unsigned char * server_random, dhe_server_key_exchange_t * server_key_ex, authentication_algorithm au)
Sign the server_key_exchange message for a DHE key exchange. The function choice an arbitrary hash algorithm for the signature (except md5,sha1). It take private key in ../certificates/ folder with name serverA.key wher A can be RSA, DSS.
Parameters
client_random : the random sent by the client in the client hello. Must point to 32 byte stream
server_random : the random sent by the server in the server hello. Must point to 32 byte stream
server_key_ex : the server key exchange message to sign.
au : the authentication algorithm.
Referenced by make_DHE_server_key_exchange().
int sign_ECDHE_server_key_ex (unsigned char * client_random, unsigned char * server_random, ecdhe_server_key_exchange_t * server_key_ex, authentication_algorithm au)
Sign the server_key_exchange message for a ECDHE key exchange. The function choice an arbitrary hash algorithm for the signature (except md5,sha1). It take private key in ../certificates/ folder with name serverA.key wher A can be RSA, ECDSA.
Parameters
client_random : the random sent by the client in the client hello. Must point to 32 byte stream
server_random : the random sent by the server in the server hello. Must point to 32 byte stream
server_key_ex : the server key exchange message to sign.
au : the authentication algorithm.
Referenced by make_ECDHE_server_key_exchange().
int verify_DHE_server_key_ex_sign (X509 * certificate, unsigned char * client_random, unsigned char * server_random, dhe_server_key_exchange_t * server_key_ex, authentication_algorithm au)
Verify the server_key_exchange message for a DHE key exchange.
Parameters
certificate : the certificate to use for verify the signature
client_random : the random sent by the client in the client hello. Must point to 32 byte stream
server_random : the random sent by the server in the server hello. Must point to 32 byte stream
server_key_ex : the server key exchange message to verify.
au : the authentication algorithm.
Referenced by make_DHE_client_key_exchange().
int verify_ECDHE_server_key_ex_sign (X509 * certificate, unsigned char * client_random, unsigned char * server_random, ecdhe_server_key_exchange_t * server_key_ex, authentication_algorithm au)
Verify the server_key_exchange message for a ECDHE key exchange.
Parameters
certificate : the certificate to use for verify the signature
client_random : the random sent by the client in the client hello. Must point to 32 byte stream
server_random : the random sent by the server in the server hello. Must point to 32 byte stream
server_key_ex : the server key exchange message to verify.
au : the authentication algorithm.
Referenced by make_ECDHE_client_key_exchange().