Advanced Programming : TLS handshake: src/ServerClientRecordProtocol.c File Reference
ServerClientRecordProtocol.c File Reference
#include "ServerClientRecordProtocol.h"
Functions
void serialize_record (record_t *r, unsigned char **message, uint16_t *messageLen)
record_t * deserialize_record (unsigned char *message, uint32_t messageLen)
int send_record (channel_t *ch, record_t *r)
void print_record (record_t *r)
void free_record (record_t *r)
Detailed Description
SSL/TLS Project
This file is an interface to the record protocol. Provide function and struct for modelling and manage record messages.
Date
Created on 23/12/15.
Copyright
Copyright © 2015 Alessandro Melloni, Andrea Francesco Vinci. All rights reserved.
Function Documentation
record_t* deserialize_record (unsigned char * message, uint32_t messageLen)
De-serialize a byte stream message of length message_len into a record struct.
Parameters
message : message received
messageLen : message length
Returns
record : the de-serialized record
Referenced by onPacketReceive().
void free_record (record_t * r)
Deallocate memory pointed by r
Parameters
r : pointer to record to free
Referenced by onPacketReceive(), and send_handshake().
void print_record (record_t * r)
Print a description of the record
Parameters
r : record to print.
Referenced by onPacketReceive(), and print_handshake().
int send_record (channel_t * ch, record_t * r)
Send record to_send over the channel ch. Note :for send record is important to set 'to' and 'from' in the channel creation.
Parameters
ch : channel to use
to_send : record to send
Returns
1 if the message was successfully sent, 0 otherwise
Referenced by onPacketReceive(), and send_handshake().
void serialize_record (record_t * r, unsigned char ** message, uint16_t * messageLen)
Serialize record in a byte stream of length message_len stored in message.
Parameters
message : pointer to null (the function allocate space for you)
messageLen : pointer to integer (will contains the message length)
Referenced by print_record(), and send_record().