Advanced Programming : TLS handshake: /Users/Darka/Dropbox/UNITN/AdvancedProgramming/Project/src/ServerClientHandshakeProtocol.c File Reference
ServerClientHandshakeProtocol.c File Reference
#include "ServerClientHandshakeProtocol.h"
Functions
record_t * make_record (handshake_t *h)
int send_handshake (channel_t *ch, handshake_t *h)
void serialize_handshake (handshake_t *h, unsigned char **stream, uint32_t *streamLen)
handshake_t * deserialize_handshake (unsigned char *message, uint32_t messageLen)
void free_handshake (handshake_t *h)
void print_handshake (handshake_t *h, int verbosity, key_exchange_algorithm kx)
Function Documentation
handshake_t* deserialize_handshake (unsigned char * message, uint32_t messageLen)
De-serialize a stream of byte into an handshake.
Parameters
message : the serialized handshake
messageLen : the message length
Returns
alloc and return an handshake struct
Referenced by onPacketReceive().
void free_handshake (handshake_t * h)
Delloc memory of handshake struct
Parameters
h : the handshake to free
Referenced by do_handshake(), and onPacketReceive().
record_t* make_record (handshake_t * h)
Referenced by send_handshake().
void print_handshake (handshake_t * h, int verbosity, key_exchange_algorithm kx)
Print an handshake struct
Parameters
h : handshake to print
verobisty : how many detail to print (0 none, 1 the binary, 2 details)
kx : the key exchange algorithm, useful in key_echange messages
Referenced by do_handshake(), and onPacketReceive().
int send_handshake (channel_t * ch, handshake_t * h)
Send an handshake through a channel
Parameters
ch : the channel to use
h : the handshake to send
Returns
1 if the send is success, 0 otherwise
Referenced by do_handshake(), and onPacketReceive().
void serialize_handshake (handshake_t * h, unsigned char ** stream, uint32_t * streamLen)
Serialize a handshake into a byte stream
Parameters
h : the handshake to serialize
stream : a pointer to NULL, it will filled with the serialized handshake
streamLen : the length of the serialized message
Referenced by backup_handshake(), make_record(), and print_handshake().