Advanced Programming : TLS handshake: /Users/Darka/Dropbox/UNITN/AdvancedProgramming/Project/include/ServerClientRecordProtocol.h File Reference
ServerClientRecordProtocol.h File Reference
#include <stdio.h>
#include "ServerClientTransportProtocol.h"
Data Structures
struct record_t
Macros
#define REV16(value) ({(value & 0x00FFU) << 8 | (value & 0xFF00U) >> 8;})
Enumerations
Functions
int send_record (channel_t *ch, record_t *to_send)
record_t * deserialize_record (unsigned char *message, uint32_t message_len)
void serialize_record (record_t *r, unsigned char **message, uint16_t *message_len)
void print_record (record_t *r)
void free_record (record_t *r)
Detailed Description
SSL/TLS Project
This file is an interface to the record protocol. Provide function and struct for modelling and manage record messages.
Date
Created on 23/12/15.
Copyright
Copyright © 2015 Alessandro Melloni, Andrea Francesco Vinci. All rights reserved.
Macro Definition Documentation
#define REV16 (value) ({(value & 0x00FFU) << 8 | (value & 0xFF00U) >> 8;})
Rotational byte for uint16
Referenced by deserialize_client_key_exchange(), deserialize_client_server_hello(), deserialize_record(), deserialize_server_key_exchange(), make_RSA_client_key_exchange(), serialize_client_key_exchange(), serialize_client_server_hello(), serialize_record(), and serialize_server_key_exchange().
Enumeration Type Documentation
enum record_type
Define the different type of record
Enumerator
HANDSHAKE
CHANGE_CIPHER_SPEC
ALERT
APPLICATION_DATA
Function Documentation
record_t* deserialize_record (unsigned char * message, uint32_t message_len)
De-serialize a byte stream message of length message_len into a record struct.
Parameters
message : message received
messageLen : message length
Returns
record : the de-serialized record
Referenced by onPacketReceive().
void free_record (record_t * r)
Deallocate memory pointed by r
Parameters
r : pointer to record to free
Referenced by onPacketReceive(), and send_handshake().
void print_record (record_t * r)
Print a description of the record
Referenced by onPacketReceive().
int send_record (channel_t * ch, record_t * to_send)
Send record to_send over the channel ch. Note :for send record is important to set 'to' and 'from' in the channel creation.
Parameters
ch : channel to use
to_send : record to send
Returns
1 if the message was successfully sent, 0 otherwise
Referenced by onPacketReceive(), and send_handshake().
void serialize_record (record_t * r, unsigned char ** message, uint16_t * message_len)
Serialize record in a byte stream of length message_len stored in message.
Parameters
message : pointer to null (the function allocate space for you)
messageLen : pointer to integer (will contains the message length)
Referenced by print_record(), and send_record().