Advanced Programming : TLS handshake: /Users/Darka/Dropbox/UNITN/AdvancedProgramming/Project/include/HandshakeMessages/ServerClientHello.h File Reference
ServerClientHello.h File Reference
#include <stdio.h>
#include <stdint.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include <openssl/rand.h>
#include "TLSConstants.h"
Data Structures
struct random_data_t
struct session_id_t
struct compression_methods_t
struct server_client_hello_t
Functions
server_client_hello_t * make_hello (session_id_t session)
void serialize_client_server_hello (server_client_hello_t *hello, unsigned char **stream, uint32_t *streamLen, channel_mode mode)
server_client_hello_t * deserialize_client_server_hello (unsigned char *stream, uint32_t streamLen, channel_mode mode)
void free_hello (server_client_hello_t *h)
void print_hello (server_client_hello_t *h)
Function Documentation
server_client_hello_t* deserialize_client_server_hello (unsigned char * stream, uint32_t streamLen, channel_mode mode)
Referenced by onPacketReceive(), and print_handshake().
void free_hello (server_client_hello_t * h)
Referenced by make_client_hello(), make_server_hello(), onPacketReceive(), and print_handshake().
server_client_hello_t* make_hello (session_id_t session)
Referenced by make_client_hello(), and make_server_hello().
void print_hello (server_client_hello_t * h)
Referenced by print_handshake().
void serialize_client_server_hello (server_client_hello_t * hello, unsigned char ** stream, uint32_t * streamLen, channel_mode mode)
Referenced by make_client_hello(), and make_server_hello().