Advanced Programming : TLS handshake: /Users/Darka/Dropbox/UNITN/AdvancedProgramming/Project/include/HandshakeMessages/ServerClientKeyExchange.h File Reference
ServerClientKeyExchange.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <openssl/hmac.h>
#include "TLSConstants.h"
Data Structures
struct ecdhe_server_key_exchange_t
struct dhe_server_key_exchange_t
struct client_key_exchange_t
Typedefs
typedef void server_key_exchange_t
Functions
void serialize_server_key_exchange (server_key_exchange_t *server_key_exchange, unsigned char **stream, uint32_t *streamLen, key_exchange_algorithm kx)
server_key_exchange_t * deserialize_server_key_exchange (unsigned char *message, uint32_t message_len, key_exchange_algorithm kx)
void print_server_key_exchange (server_key_exchange_t *server_key_exchange, key_exchange_algorithm kx)
void free_server_key_exchange (server_key_exchange_t *server_key_ex, key_exchange_algorithm kx)
void serialize_client_key_exchange (client_key_exchange_t *client_key_exchange, unsigned char **stream, uint32_t *streamLen)
client_key_exchange_t * deserialize_client_key_exchange (unsigned char *message, uint32_t message_len)
void print_client_key_exchange (client_key_exchange_t *client_key_exchange)
void free_client_key_exchange (client_key_exchange_t *client_key_exchange)
Typedef Documentation
typedef void server_key_exchange_t
Function Documentation
client_key_exchange_t* deserialize_client_key_exchange (unsigned char * message, uint32_t message_len)
Referenced by onPacketReceive(), and print_handshake().
server_key_exchange_t* deserialize_server_key_exchange (unsigned char * message, uint32_t message_len, key_exchange_algorithm kx)
Referenced by onPacketReceive(), and print_handshake().
void free_client_key_exchange (client_key_exchange_t * client_key_exchange)
Referenced by make_client_key_exchange(), onPacketReceive(), and print_handshake().
void free_server_key_exchange (server_key_exchange_t * server_key_ex, key_exchange_algorithm kx)
Referenced by do_handshake(), and print_handshake().
void print_client_key_exchange (client_key_exchange_t * client_key_exchange)
Referenced by print_handshake().
void print_server_key_exchange (server_key_exchange_t * server_key_exchange, key_exchange_algorithm kx)
Referenced by print_handshake().
void serialize_client_key_exchange (client_key_exchange_t * client_key_exchange, unsigned char ** stream, uint32_t * streamLen)
Referenced by make_client_key_exchange().
void serialize_server_key_exchange (server_key_exchange_t * server_key_exchange, unsigned char ** stream, uint32_t * streamLen, key_exchange_algorithm kx)
Referenced by make_server_key_exchange().