Advanced Programming : TLS handshake: include/ServerClientTransportProtocol.h File Reference
ServerClientTransportProtocol.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <pthread.h>
#include <time.h>
Data Structures
struct packet_transport_t
struct channel_t
Macros
#define DELAY_TIME 50
Typedefs
typedef struct channel_t channel_t
Functions
channel_t * create_channel (char *fileName, char *channelFrom, char *channelTo)
int set_on_receive (channel_t *ch, void(*onPacketReceive)(channel_t *ch, packet_transport_t *p))
int send_packet (channel_t *ch, packet_transport_t *p)
int start_listener (channel_t *ch)
void wait_channel (channel_t *ch)
void stop_channel (channel_t *ch)
packet_transport_t * create_packet (char *source, char *destination, unsigned char *message, uint32_t message_length)
void free_packet (packet_transport_t *p)
Detailed Description
SSL/TLS Project
Basic client/server communication through file. It substitutes the transport layer in OSI stack.
PROTOCOL: The protocol is very simple 8 byte for source 8 byte for receiver 4 byte for packet length message
Both server and client, after reading a message, blank the file both server and client cannot write if the file is not blank, they wait
Date
Created on 22/12/15.
Copyright
Copyright © 2015 Alessandro Melloni, Andrea Francesco Vinci. All rights reserved.
Macro Definition Documentation
#define DELAY_TIME 50
the time to wait between 2 readings of the file. Important to don't use too much CPU.
Referenced by reader().
Typedef Documentation
typedef struct channel_t channel_t
Function Documentation
channel_t* create_channel (char * fileName, char * channelFrom, char * channelTo)
Create a server/client channel using the fileName as communication channel
Parameters
fileName file name of the channel
channelFrom name of the channel owner
channelTo name of the other peer
Returns
the created channel
Referenced by do_handshake().
packet_transport_t* create_packet (char * source, char * destination, unsigned char * message, uint32_t message_length)
Create a packet starting from a byte stream source and destination
Parameters
source packet source
destination packet receiver
message message stream to be encapsulate into packet
message_length message lenght
Returns
a pointer to a built packet
Create a packet starting from a byte stream source and destination
Parameters
source packet source
destination packet receiver
message message stream to be encapsulated into packet
message_length message lenght
Returns
a pointer to a built packet
Referenced by deserialize_packet(), and send_record().
void free_packet (packet_transport_t * p)
Deallocate memory allocated by packet
Parameters
p pointer to packet to free
Referenced by onPacketReceive(), reader(), and send_record().
int send_packet (channel_t * ch, packet_transport_t * p)
Send a message through the channel ch
Parameters
ch channel to be used
p pointer to packet to be sent
Returns
: 1 if the message was sent, 0 otherwise
Referenced by send_record().
int set_on_receive (channel_t * ch, void(*)(channel_t *ch, packet_transport_t *p) onPacketReceive)
Set the function to be called when a message is received
Parameters
ch channel interested
onPacketReceive pointer to the function to be called
Returns
: 1 if the function was set, 0 otherwise
Set the function to be called when a message is received
Parameters
ch channel interested
onPacketReceive pointer to the function to call
Returns
: 1 if the function was set, 0 otherwise
Referenced by do_handshake().
int start_listener (channel_t * ch)
Start the channel. We open another thread for the reading and the current thread for writing. From now on (if the operation is successful) the client/server read continously from channel. (to STOP use stop())
Parameters
ch channel to start
Returns
: 1 if the thread was started, 0 otherwise
Start the channel. We open another thread for the reading and the current thread for writing. From now on (if the operation is succesfull) the client/server read continously from channel. (to STOP use stop())
Parameters
ch channel to start
Returns
: 1 if the thread was started, 0 otherwise
Referenced by do_handshake().
void stop_channel (channel_t * ch)
Stop the reading/writing thread and the channel. Note: the function doesn't free the channel.
Parameters
ch channel to stop
Referenced by onPacketReceive().
void wait_channel (channel_t * ch)
Stop the caller and wait until stop() is called
Parameters
ch the channel to wait
Referenced by do_handshake().