Advanced Programming : TLS handshake: include/ServerClientHandshakeProtocol.h File Reference
ServerClientHandshakeProtocol.h File Reference
#include <stdio.h>
#include <stdint.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include "ServerClientRecordProtocol.h"
#include "TLSConstants.h"
#include "ServerClientHello.h"
#include "Certificate.h"
#include "ServerClientKeyExchange.h"
Data Structures
struct handshake_t
Functions
int send_handshake (channel_t *ch, handshake_t *h)
void serialize_handshake (handshake_t *h, unsigned char **stream, uint32_t *streamLen)
handshake_t * deserialize_handshake (unsigned char *message, uint32_t messageLen)
void print_handshake (handshake_t *h, int verbosity, key_exchange_algorithm kx)
void free_handshake (handshake_t *h)
Detailed Description
SSL/TLS Project
This file is used to mange the handshake protocol
Date
Created on 27/12/15.
Copyright
Copyright © 2015 Alessandro Melloni, Andrea Francesco Vinci. All rights reserved.
Function Documentation
handshake_t* deserialize_handshake (unsigned char * message, uint32_t messageLen)
De-serialize a stream of byte into an handshake.
Parameters
message : the serialized handshake
messageLen : the message length
Returns
alloc and return an handshake struct
Referenced by onPacketReceive().
void free_handshake (handshake_t * h)
Delloc memory of handshake struct
Parameters
h : the handshake to free
Referenced by do_handshake(), and onPacketReceive().
void print_handshake (handshake_t * h, int verbosity, key_exchange_algorithm kx)
Print the handshake struct
Parameters
h : handshake to print
verbosity : how many detail to print (0 none, 1 the binary, 2 details,3 record)
kx : the key exchange algorithm, useful in key_echange messages
Referenced by do_handshake(), and onPacketReceive().
int send_handshake (channel_t * ch, handshake_t * h)
Send an handshake through a channel
Parameters
ch : the channel to use
h : the handshake to send
Returns
1 if the send is success, 0 otherwise
Referenced by do_handshake(), and onPacketReceive().
void serialize_handshake (handshake_t * h, unsigned char ** stream, uint32_t * streamLen)
Serialize a handshake into a byte stream
Parameters
h : the handshake to serialize
stream : a pointer to NULL, it will filled with the serialized handshake
streamLen : the length of the serialized message
Referenced by backup_handshake(), make_record(), and print_handshake().