Advanced Programming : TLS handshake: src/TLS.c File Reference
TLS.c File Reference
#include "TLS.h"
Functions
void backup_handshake (TLS_parameters_t *TLS_param, handshake_t *h)
handshake_t * make_client_hello (unsigned char *client_random, cipher_suite_t cipher_suite_list[], int cipher_suite_len)
void make_RSA_client_key_exchange (TLS_parameters_t *TLS_param, client_key_exchange_t *client_key_ex)
void make_DHE_client_key_exchange (TLS_parameters_t *TLS_param, client_key_exchange_t *client_key_ex)
void make_ECDHE_client_key_exchange (TLS_parameters_t *TLS_param, client_key_exchange_t *client_key_ex)
handshake_t * make_client_key_exchange (TLS_parameters_t *TLS_param, uint16_t key_ex_alg)
record_t * make_change_cipher_spec ()
handshake_t * make_finished_message (TLS_parameters_t *TLS_param)
handshake_t * make_server_hello (TLS_parameters_t *TLS_param, server_client_hello_t *client_hello)
handshake_t * make_certificate (TLS_parameters_t *TLS_param)
dhe_server_key_exchange_t * make_DHE_server_key_exchange (TLS_parameters_t *TLS_param)
ecdhe_server_key_exchange_t * make_ECDHE_server_key_exchange (TLS_parameters_t *TLS_param)
handshake_t * make_server_key_exchange (TLS_parameters_t *TLS_param)
handshake_t * make_server_hello_done ()
Detailed Description
SSL/TLS Project
This file provide a set of function for the TLS handshake. The function are used for make TLS message for both server and client.
Date
Created on 13/01/16.
Copyright
Copyright © 2016 Alessandro Melloni, Andrea Francesco Vinci. All rights reserved.
Function Documentation
void backup_handshake (TLS_parameters_t * TLS_param, handshake_t * h)
Append the handshake h to the handshake_messages field of TLS_param
Parameters
TLS_param : connection parameters
h : the handshake to append
Referenced by do_handshake(), and onPacketReceive().
handshake_t* make_certificate (TLS_parameters_t * TLS_param)
Make the certificate message for the server. That message depends on the authentication algorithm hence we require the connection parameters. The function also sets the certificate in the connection parameters for feature uses.
Parameters
TLS_param : connection parameters
Returns
the certificate handshake message
Referenced by onPacketReceive().
record_t* make_change_cipher_spec ()
Make the change cipher spec record message. This message is simple and doesn't require any parameter.
Returns
the change cipher spec record
Referenced by onPacketReceive().
handshake_t* make_client_hello (unsigned char * client_random, cipher_suite_t cipher_suite_list[], int cipher_suite_len)
Given an array of cipher suite make a client hello message. The function also fill the random field using the time stamp and a random generator(openssl)
Parameters
client_random : the random setted in the client hello
cipher_suite_list : an array of cipher suite to add in the client hello
cipher_suite_len : the number of cipher suite in the list
Returns
the hello client handshake message
Referenced by do_handshake().
handshake_t* make_client_key_exchange (TLS_parameters_t * TLS_param, uint16_t key_ex_alg)
Given the information in the TLS_parameter and the key exchange algorithm return the handshake of the client key exchange. That include compute the pre-master key. It also compute the master secret and set in the TLS_param.
Parameters
TLS_param : the parameters of the connection
key_ex_alg : the key exchange algorithm of the handshake
Returns
the client key exchange handshake message
Referenced by onPacketReceive().
void make_DHE_client_key_exchange (TLS_parameters_t * TLS_param, client_key_exchange_t * client_key_ex)
Make the client key exchange message for DHE key exchange. This function is called from make_client_key_exchange if the key exchange is DHE.
Parameters
client_key_ex : the client key exchange message
TLS_param : the connection parameters
Referenced by make_client_key_exchange().
dhe_server_key_exchange_t* make_DHE_server_key_exchange (TLS_parameters_t * TLS_param)
Make the server key exchange for DHE key exchange. It computes the DH parameters and save the message in the connection parameters TLS_param.
Parameters
TLS_param : connection parameters
Returns
the dhe_server_key_exchange struct
Referenced by make_server_key_exchange().
void make_ECDHE_client_key_exchange (TLS_parameters_t * TLS_param, client_key_exchange_t * client_key_ex)
Make the client key exchange message for ECDHE key exchange. This function is called from make_client_key_exchange if the key exchange is ECDHE.
Parameters
client_key_ex : the client key exchange message
TLS_param : the connection parameters
Referenced by make_client_key_exchange().
ecdhe_server_key_exchange_t* make_ECDHE_server_key_exchange (TLS_parameters_t * TLS_param)
Make the server key exchange for ECDHE key exchange. It computes the ECDHE parameters using the secp256k1 curve and save the message in the connection parameters TLS_param.
Parameters
TLS_param : connection parameters
Returns
the ecdhe_server_key_exchange struct
Referenced by make_server_key_exchange().
handshake_t* make_finished_message (TLS_parameters_t * TLS_param)
Given the connection parameters compute the finished message. Note in the TLS protocol this message is encrypted.
Parameters
TLS_param : the connection parameters
Returns
the finished handshake message
Referenced by onPacketReceive().
void make_RSA_client_key_exchange (TLS_parameters_t * TLS_param, client_key_exchange_t * client_key_ex)
Make the client key exchange message for RSA key exchange. This function is called from make_client_key_exchange if the key exchange is RSA.
Parameters
client_key_ex : the client key exchange message
TLS_param : the connection parameters
Referenced by make_client_key_exchange().
handshake_t* make_server_hello (TLS_parameters_t * TLS_param, server_client_hello_t * client_hello)
Given the client hello message the function makes the server hello. It choices a random cipher suite among the those provided by the client. The function also fill the random field using the time stamp and a random generator(openssl)
Parameters
TLS_param : the connection parameters
client_hello : the received client hello.
Returns
the hello server handshake message
Referenced by onPacketReceive().
handshake_t* make_server_hello_done ()
Make the server hello done message. This message is simple and doesn't require any parameter.
Returns
the server hello done handshake message
Referenced by onPacketReceive().
handshake_t* make_server_key_exchange (TLS_parameters_t * TLS_param)
Make the server key exchange handshake message. The function also sets the message in the connection parameters for compute the master key in the client key exchange message.
Parameters
TLS_param : connection parameters
Returns
the server key exchange handshake message
Referenced by onPacketReceive().