Advanced Programming : TLS handshake: /Users/Darka/Dropbox/UNITN/AdvancedProgramming/Project/include/TLSConstants.h File Reference
TLSConstants.h File Reference
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <openssl/hmac.h>
Data Structures
struct cipher_suite_t
Macros
#define REV16(value) ({(value & 0x00FFU) << 8 | (value & 0xFF00U) >> 8;})
#define REV32(value) ({(value & 0x000000FFU) << 24 | (value & 0x0000FF00U) << 8 |(value & 0x00FF0000U) >> 8 | (value & 0xFF000000U) >> 24;})
Enumerations
Functions
const EVP_MD * get_hash_function (hash_algorithm h)
cipher_suite_t get_cipher_suite_by_id (uint16_t id)
cipher_suite_t get_cipher_suite_by_name (char *name)
int get_cipher_suites (key_exchange_algorithm kx, hash_algorithm h, authentication_algorithm au, cipher_suite_t array[])
Variables
const int NUM_CIPHER_SUITE
Detailed Description
SSL/TLS Project
This file contains a set of constants used in the handshake protocol and function interface for manage the supported cipher suite.
Date
Created on 24/12/15.
Copyright
Copyright © 2015 Alessandro Melloni, Andrea Francesco Vinci. All rights reserved.
Macro Definition Documentation
#define REV16 (value) ({(value & 0x00FFU) << 8 | (value & 0xFF00U) >> 8;})
Rotational byte for uint16
#define REV32 (value) ({(value & 0x000000FFU) << 24 | (value & 0x0000FF00U) << 8 |(value & 0x00FF0000U) >> 8 | (value & 0xFF000000U) >> 24;})
Rotational byte for uint32
Referenced by deserialize_certificate_message(), deserialize_client_server_hello(), deserialize_handshake(), serialize_certificate_message(), serialize_client_server_hello(), and serialize_handshake().
Enumeration Type Documentation
anonymous enum
Enumerator
HELLO_REQUEST
CLIENT_HELLO
SERVER_HELLO
CERTIFICATE
SERVER_KEY_EXCHANGE
CERTIFICATE_REQUEST
SERVER_DONE
CERTIFICATE_VERIFY
CLIENT_KEY_EXCHANGE
FINISHED
enum authentication_algorithm
Different type of authentication algorithm
Enumerator
NONE_AU
No algorithm
RSA_AU
RSA signature
DSS_AU
DSA signature
ECDSA_AU
ECDSA signature
enum channel_mode
Enum used for set the packet mode e.g. server_hello, client_hello
Enumerator
SERVER_MODE
CLIENT_MODE
enum hash_algorithm
Different type of hash algorithm
Enumerator
NONE_H
No hash
MD5_H
MD5
SHA1_H
SHA 1
SHA224_H
SHA 224
SHA256_H
SHA 256
SHA384_H
SHA 384
SHA512_H
SHA 512
enum key_exchange_algorithm
Different type of key exchange algorithm
Enumerator
NONE_KX
No algorithm
RSA_KX
RSA algorithm
DHE_KX
Ephemeral Diffie Hellman
ECDHE_KX
Ephemeral Diffie Hellman over elliptic curve
enum TLS_version
Enumerator
SSL3_0
SSL 3
TLS1_0
TLS 1.0
TLS1_1
TLS 1.1
TLS1_2
TLS 1.2
Function Documentation
cipher_suite_t get_cipher_suite_by_id (uint16_t id)
Given the id of a cipher suite return the cipher suite struct.
Parameters
id : cipher suite id
Returns
cipher suite struct with id id
Referenced by deserialize_client_server_hello(), main(), and make_server_hello().
cipher_suite_t get_cipher_suite_by_name (char * name)
Given the cipher suite name return the cipher suite struct.
Parameters
name : cipher suite name
Returns
cipher suite struct with name name
Referenced by main().
int get_cipher_suites (key_exchange_algorithm kx, hash_algorithm h, authentication_algorithm au, cipher_suite_t array[])
Fill array[] with all cipher suite that has key exchange kx, hash algorithm h and authentication algorithm au.
Parameters
kx : the key exchange algorithm (if NONE_KX the function consider all key exchange algorithm)
h : the hash algorithm (if NONE_H the function consider all hash algorithm)
au : the authentication algorithm (if NONE_AU the function consider all authentication algorithm)
array[] : an empty array of size NUM_CIPHER_SUITE.
Returns
the number of cipher suite loaded in array[]
Referenced by main().
const EVP_MD* get_hash_function (hash_algorithm h)
Get the hash algorithm starting from the hash id.
Parameters
h : the hash algorithm used
Returns
an EVP_MD struct used for compute digest
Referenced by compute_set_master_key_DHE(), compute_set_master_key_ECDHE(), compute_set_master_key_RSA(), make_DHE_client_key_exchange(), make_ECDHE_client_key_exchange(), make_finished_message(), and make_RSA_client_key_exchange().
Variable Documentation
const int NUM_CIPHER_SUITE
The number of supported cipher suite
Referenced by get_cipher_suite_by_id(), get_cipher_suite_by_name(), get_cipher_suites(), and main().