Advanced Programming : TLS handshake: /Users/Darka/Dropbox/UNITN/AdvancedProgramming/Project/src/TLSConstants.c File Reference
TLSConstants.c File Reference
#include "TLSConstants.h"
Functions
const EVP_MD * get_hash_function (hash_algorithm h)
int get_cipher_suites (key_exchange_algorithm kx, hash_algorithm h, authentication_algorithm au, cipher_suite_t array[])
cipher_suite_t get_cipher_suite_by_name (char *name)
cipher_suite_t get_cipher_suite_by_id (uint16_t id)
Variables
const int NUM_CIPHER_SUITE = 62
cipher_suite_t cipher_suite_list []
Detailed Description
SSL/TLS Project
This file contains a set of constants used in the handshake protocol and function implementation for manage the supported cipher suite.
Date
Created on 24/12/15.
Copyright
Copyright © 2015 Alessandro Melloni, Andrea Francesco Vinci. All rights reserved.
Function Documentation
cipher_suite_t get_cipher_suite_by_id (uint16_t id)
Given the id of a cipher suite return the cipher suite struct.
Parameters
id : cipher suite id
Returns
cipher suite struct with id id
Referenced by deserialize_client_server_hello(), main(), and make_server_hello().
cipher_suite_t get_cipher_suite_by_name (char * name)
Given the cipher suite name return the cipher suite struct.
Parameters
name : cipher suite name
Returns
cipher suite struct with name name
Referenced by main().
int get_cipher_suites (key_exchange_algorithm kx, hash_algorithm h, authentication_algorithm au, cipher_suite_t array[])
Fill array[] with all cipher suite that has key exchange kx, hash algorithm h and authentication algorithm au.
Parameters
kx : the key exchange algorithm (if NONE_KX the function consider all key exchange algorithm)
h : the hash algorithm (if NONE_H the function consider all hash algorithm)
au : the authentication algorithm (if NONE_AU the function consider all authentication algorithm)
array[] : an empty array of size NUM_CIPHER_SUITE.
Returns
the number of cipher suite loaded in array[]
Referenced by main().
const EVP_MD* get_hash_function (hash_algorithm h)
Get the hash algorithm starting from the hash id.
Parameters
h : the hash algorithm used
Returns
an EVP_MD struct used for compute digest
Referenced by compute_set_master_key_DHE(), compute_set_master_key_ECDHE(), compute_set_master_key_RSA(), make_DHE_client_key_exchange(), make_ECDHE_client_key_exchange(), make_finished_message(), and make_RSA_client_key_exchange().
Variable Documentation
cipher_suite_t cipher_suite_list[]
List of supported cipher suite
const int NUM_CIPHER_SUITE = 62
The number of supported cipher suite
Referenced by get_cipher_suite_by_id(), get_cipher_suite_by_name(), get_cipher_suites(), and main().