Advanced Programming : TLS handshake: include/TLS.h File Reference
TLS.h File Reference
#include <stdio.h>
#include <time.h>
#include "ServerClientHandshakeProtocol.h"
#include "ServerClientRecordProtocol.h"
#include "Crypto.h"
Data Structures
struct TLS_parameters_t
Functions
handshake_t * make_client_hello (unsigned char *client_random, cipher_suite_t cipher_suite_list[], int cipher_suite_len)
handshake_t * make_client_key_exchange (TLS_parameters_t *TLS_param, uint16_t key_ex_alg)
record_t * make_change_cipher_spec ()
handshake_t * make_finished_message (TLS_parameters_t *TLS_param)
handshake_t * make_server_hello (TLS_parameters_t *TLS_param, server_client_hello_t *client_hello)
handshake_t * make_certificate (TLS_parameters_t *TLS_param)
handshake_t * make_server_key_exchange (TLS_parameters_t *TLS_param)
handshake_t * make_server_hello_done ()
void backup_handshake (TLS_parameters_t *TLS_param, handshake_t *h)
Detailed Description
SSL/TLS Project
This file provide a set of function for the TLS handshake. The function are used to make TLS message for both server and client.
Date
Created on 13/01/16.
Copyright
Copyright © 2016 Alessandro Melloni, Andrea Francesco Vinci. All rights reserved.
Function Documentation
void backup_handshake (TLS_parameters_t * TLS_param, handshake_t * h)
Append the handshake h to the handshake_messages field of TLS_param
Parameters
TLS_param connection parameters
h the handshake to append
Referenced by do_handshake(), and onPacketReceive().
handshake_t* make_certificate (TLS_parameters_t * TLS_param)
Make the certificate message for the server. That message depends on the authentication algorithm hence we require the connection parameters. The function also sets the certificate in the connection parameters for further uses.
Parameters
TLS_param connection parameters
Returns
the certificate handshake message
Referenced by onPacketReceive().
record_t* make_change_cipher_spec ()
Make the change cipher spec record message. This message is simple and doesn't require any parameter.
Returns
the change cipher spec record
Referenced by onPacketReceive().
handshake_t* make_client_hello (unsigned char * client_random, cipher_suite_t cipher_suite_list[], int cipher_suite_len)
Given an array of cipher suites make a client hello message. The function also fills the random field using the UNIX time stamp and a random generator (OpenSSL)
Parameters
client_random the random set in the client hello
cipher_suite_list an array of cipher suites to add in the client hello
cipher_suite_len the number of cipher suites in the list
Returns
the hello client handshake message
Given an array of cipher suites, make a client hello message. The function also fills the random field using the time stamp and a random generator (OpenSSL)
Parameters
client_random the random set in the client hello
cipher_suite_list an array of cipher suites to add to the client hello
cipher_suite_len the number of cipher suites in the list
Returns
the client hello handshake message
Referenced by do_handshake().
handshake_t* make_client_key_exchange (TLS_parameters_t * TLS_param, uint16_t key_ex_alg)
Given the information in TLS_parameter and the key exchange algorithm return the handshake of the client key exchange. That includes to compute the pre-master key. It also computes the master secret and set in TLS_param.
Parameters
TLS_param the parameters of the connection
key_ex_alg the key exchange algorithm of the handshake
Returns
the client key exchange handshake message
Given the information in TLS_parameter and the key exchange algorithm return the handshake of the client key exchange. That includes to compute the pre-master key. It also computes the master secret and set it in TLS_param.
Parameters
TLS_param the parameters of the connection
key_ex_alg the key exchange algorithm of the handshake
Returns
the client key exchange handshake message
Referenced by onPacketReceive().
handshake_t* make_finished_message (TLS_parameters_t * TLS_param)
Given the connection parameters compute the finished message. Note: TLS protocol requires this message to be encrypted.
Parameters
TLS_param the connection parameters
Returns
the finished handshake message
Referenced by onPacketReceive().
handshake_t* make_server_hello (TLS_parameters_t * TLS_param, server_client_hello_t * client_hello)
Given the client hello message the function makes the server hello. It chooses a random cipher suite among those provided by the client. The function also fills the random field using the UNIX time stamp and a random generator (OpenSSL)
Parameters
TLS_param the connection parameters
client_hello the received client hello.
Returns
the hello server handshake message
Given the client hello message the function makes the server hello. It chooses a random cipher suite among those provided by the client. The function also fills the random field using the time stamp and a random generator (OpenSSL)
Parameters
TLS_param the connection parameters
client_hello the received client hello.
Returns
the hello server handshake message
Referenced by onPacketReceive().
handshake_t* make_server_hello_done ()
Make the server hello done message. This message is simple and doesn't require any parameter.
Returns
the server hello done handshake message
Referenced by onPacketReceive().
handshake_t* make_server_key_exchange (TLS_parameters_t * TLS_param)
Make the server key exchange handshake message. The function also sets the message in the connection parameters to compute the master key in the client key exchange message.
Parameters
TLS_param connection parameters
Returns
the server key exchange handshake message
Referenced by onPacketReceive().