Advanced Programming : TLS handshake: /Users/Darka/Dropbox/UNITN/AdvancedProgramming/Project/src/Target/client.c File Reference
client.c File Reference
#include <stdio.h>
#include <string.h>
#include "TLS.h"
Macros
#define USAGE
Functions
void onPacketReceive (channel_t *ch, packet_basic_t *p)
void do_handshake (int to_send_cipher_suite_len, cipher_suite_t to_send_cipher_suite[])
int main (int argc, char **argv)
Variables
int v = 0
TLS_parameters_t TLS_param
Macro Definition Documentation
#define USAGE
Value:
"TLSClient: TLS1.2 version handshake\n"\
                "\n"\
                "Usage:  \n"\
                "  TLSClient [args] \n"\
                " \n"\
                "Options: \n"\
                "  Specify cipher suite id (not hex) \n"\
                "    -c  --cipher_id        [id]\n"\
                "   \n"\
                "  Cipher suite name     \n"\
                "    -n  --name             [name]\n"\
                "   \n"\
                "  Specify key exchange    \n"\
                "    -x  --key_exchange    (RSA|DHE|ECDHE)  \n"\
                "   \n"\
                "  Specify authentication algorithm \n"\
                "    -a  --auth_algorithm  (RSA|DSS|ECDSA) \n"\
                " \n"\
                "  Specify verbosity \n"\
                "    -v     0 default (1|2) \n"\
                " \n"\
                "  Specify hash algorithm \n"\
                "    -h  --hash_algorithm  (MD5|SHA1|SHA224|SHA256|SHA384|SHA512) \n"\
                " \n"\
                "  Show supported cipher suites \n"\
                "    -l --list\n"\
                " \n"\
                "  Show this help \n"\
                "    --help \n\n"
Referenced by main().
Function Documentation
void do_handshake (int to_send_cipher_suite_len, cipher_suite_t to_send_cipher_suite[])
Referenced by main().
int main (int argc, char ** argv)
void onPacketReceive (channel_t * ch, packet_basic_t * p)
Referenced by do_handshake(), and set_on_receive().
Variable Documentation
TLS_parameters_t TLS_param
int v = 0
Referenced by do_handshake(), main(), and onPacketReceive().