Advanced Programming : TLS handshake: src/Target/server.c File Reference
server.c File Reference
#include <stdio.h>
#include "TLS.h"
Macros
#define USAGE
Functions
void print_random ()
void print_master_secret ()
void compute_set_master_key_RSA (client_key_exchange_t *client_key_exchange)
void compute_set_master_key_DHE (client_key_exchange_t *client_key_exchange)
void compute_set_master_key_ECDHE (client_key_exchange_t *client_key_exchange)
void onPacketReceive (channel_t *channel, packet_transport_t *p)
void do_handshake ()
int main (int argc, char **argv)
Variables
int verbosity = 0
TLS_parameters_t TLS_param
Macro Definition Documentation
#define USAGE
Value:
"TLSClient: TLS1.2 version handshake\n"\
                "\n"\
                "Usage:\n"\
                " TLSServer [args]\n"\
                "\n"\
                "Options: \n"\
                " Set verbosity\n"\
                "   -v              (0 default only handshake name \n"\
                "                   |1 handshake binary\n"\
                "                   |2 handshake binary and mesages description\n"\
                "                   |3 record bynary and messages description)\n"\
                "\n"\
                " Show this help\n"\
                "   --help\n\n"
String with program arguments
Referenced by main().
Function Documentation
void compute_set_master_key_DHE (client_key_exchange_t * client_key_exchange)
Compute the master key for DHE using the previous server key exchange stored in TLS_param and the client key exchange. The master key, master key length is stored also in TLS_param.
Parameters
client_key_exchange the client key exchange sent by client
Referenced by onPacketReceive().
void compute_set_master_key_ECDHE (client_key_exchange_t * client_key_exchange)
Compute the master key for ECDHE using the previous server key exchange stored in TLS_param and the client key exchange. The master key, master key length is stored also in TLS_param.
Parameters
client_key_exchange the client key exchange sent by client
Referenced by onPacketReceive().
void compute_set_master_key_RSA (client_key_exchange_t * client_key_exchange)
Compute the master key for RSA using the previous server key exchange stored in TLS_param and the client key exchange. The master key, master key length is stored also in TLS_param.
Parameters
client_key_exchange the client key exchange sent by client
Referenced by onPacketReceive().
void do_handshake ()
Do the handshake
Referenced by main().
int main (int argc, char ** argv)
void onPacketReceive (channel_t * channel, packet_transport_t * p)
Function called from transport protocol when a message is received
Parameters
channel the communication channel
p the received packet
Referenced by do_handshake().
void print_master_secret ()
void print_random ()
Variable Documentation
TLS_parameters_t TLS_param
connection parameters
int verbosity = 0
verbosity of the output
Referenced by main(), and onPacketReceive().